# Build settings
[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

# Headers for security and proper content delivery
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https: blob:; script-src 'self' 'unsafe-inline' https://identity.netlify.com https://www.youtube.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://www.youtube.com;"

# Cache headers for performance
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/javascript"

# Netlify Identity settings
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

# Enable Netlify Identity
[context.production.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Form handling
[[forms]]
  name = "contact"

# Redirects for SPA-like behavior
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
