site_title: "Mamello Makhele - Public Health Leader"
site_description: "Fulbright Scholar and Bill Gates Hero in the Field, dedicated to transforming maternal and child health outcomes"
name: "Mamello Makhele"
job_title: "Public Health Leader & PhD Researcher"
email: "mamello.makhele@unmc.edu"
linkedin: "https://linkedin.com/in/mamello-makhele"
github: ""
profile_image: ""
